name: PR required labels check
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize, reopened]
jobs:
  check-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Get sha commit
        run: git rev-parse HEAD
