name: Pass commit SHA to variable
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize, reopened]
jobs:
  commit_sha:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get sha commit
        id: get_commit
        run: |
          echo "COMMIT_SHA=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
      - name: Show message
        run: echo "commit number ${{steps.get_commit.outputs.COMMIT_SHA}}"
